import "bootstrap";
import "./subcategories";
import $ from 'jquery';
import { initUpdateNavbarOnScroll } from '../components/navbar.js';
import { initDropdownClick } from './dropdown';
import { categorySelector } from './categoryselector';
initUpdateNavbarOnScroll();
initDropdownClick();
window.$ = $;
window.jQuery = $;
categorySelector();
